# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
trigger:
  branches:
    include:
    - master
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: $(BuildParameters.TestProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
      zipAfterPublish: True
#  - task: AzureAppServiceManage@0
#    displayName: 'Restart Azure App Service: QuickAppSimio'
#    enabled: False
#    inputs:
#      ConnectedServiceName: ae32d06c-c3e3-4f67-8383-94b7a30bfe1a
#      Action: Restart Azure App Service
#      WebAppName: QuickAppSimio
#  - task: AzureRmWebAppDeployment@4
#    displayName: 'Azure App Service Deploy: SIMIO-DEV-SIMIOAPP'
#    enabled: False
#    inputs:
#      ConnectedServiceName: ae32d06c-c3e3-4f67-8383-94b7a30bfe1a
#      WebAppName: SIMIO-DEV-SIMIOAPP
#      Package: $(build.artifactstagingdirectory)/**/*.zip
#      UseWebDeploy: true
#      DeploymentType: zipDeploy
#  - task: AzureRmWebAppDeployment@4
#    displayName: 'Azure App Service Deploy: SIMIO-DEV-SIMIOAPP'
#    enabled: False
#    inputs:
#      ConnectedServiceName: ae32d06c-c3e3-4f67-8383-94b7a30bfe1a
#      WebAppName: SIMIO-PROD-SIMIOAPP
#      Package: $(build.artifactstagingdirectory)/**/*.zip
#      UseWebDeploy: true
#      DeploymentType: zipDeploy
#      TakeAppOfflineFlag: false
#      RemoveAdditionalFilesFlag: true
#  - task: PublishBuildArtifacts@1
#    displayName: Publish Artifact
#    condition: succeededOrFailed()
#    inputs:
#      PathtoPublish: $(build.artifactstagingdirectory)
#      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'